### PR TITLE
Added Decrees from Better Decrees Mod

### PR DESCRIPTION
**Pull request by Unintuition-Time**
To integrate the Better Decrees data into Babylon Core

### CODE REVIEW

**Comment by Unintuition-Time** [comment]
Forgot to add the rest because I got home late and have small brain, this is ready now except for the dds files which idk what to do with

**Comment by Unintuition-Time** [comment]
Ready for review

**Comment by HiddeLekanne** [comment]
You seemed to miss the events/decree_events.txt?

**Comment by Unintuition-Time** [comment]
> You seemed to miss the events/decree_events.txt?

I have it there, it's under events

**Comment by HiddeLekanne** [comment]
> > You seemed to miss the events/decree_events.txt?
> 
> I have it there, it's under events

It's in common/events xd thats not valid

**Comment by Unintuition-Time** [comment]
> > > You seemed to miss the events/decree_events.txt?
> > 
> > 
> > I have it there, it's under events
> 
> It's in common/events xd thats not valid

My bad, I got it fixed now I think

**Review by HiddeLekanne — APPROVED** [review]

**Pull request merged**
